stages:
  - test

image: python:3.11

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version ; pip --version  # For debugging

test:
  before_script:
    - ./prepare.bash
  script:
    - pip install pip poetry
    - poetry install
    - poetry run pytest
