stages:
  - test

image: python:3.11

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version ; pip --version # For debugging
  - python -m venv venv
  - bash ./venv/bin/activate
  - pip install --upgrade pip
  - pip install .
  - ./prepare.bash

Integration Tests:
  stage: test
  script:
    - pytest
